package com.netease.pineapple.common.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.netease.pineapple.common.bean.HomeListBean;

import com.netease.pineapple.common.db.HomeListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeListBeanDaoConfig;

    private final HomeListBeanDao homeListBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeListBeanDaoConfig = daoConfigMap.get(HomeListBeanDao.class).clone();
        homeListBeanDaoConfig.initIdentityScope(type);

        homeListBeanDao = new HomeListBeanDao(homeListBeanDaoConfig, this);

        registerDao(HomeListBean.class, homeListBeanDao);
    }
    
    public void clear() {
        homeListBeanDaoConfig.clearIdentityScope();
    }

    public HomeListBeanDao getHomeListBeanDao() {
        return homeListBeanDao;
    }

}
